config/routes.rb
Rails.application.routes.draw do
  resources :vehicles do
    match '/scrape', to: 'vehicles#scrape', via: :post, on: :collection
  end

  root to: 'vehicles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  def self.to_csv
    attributes = %w{title stock_type exterior_color interior_color transmission drivetrain price miles created_at}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.find_each do |vehicle|
        csv << attributes.map{ |attr| vehicle.send(attr) }
      end
    end
  end
end

#Simple csv generator without options (attributes and column_names are built-in methods)
=begin
CSV.generate do |csv|
  csv << column_names
  all.each do |vehicle|
     csv << vehicle.attributes.values_at(*column_names)
  end
end
=end

app/models/vehicles_spider.rb
class VehiclesSpider < Kimurai::Base
  @name = 'vehicles_spider'
  @engine = :mechanize

  def self.process(url)
    @start_urls = [url]
    self.crawl!
  end

  def parse(response, url:, data: {})
    response.xpath("//div[@class='shop-srp-listings__listing-container']").each do |vehicle|
      item = {}

      item[:title]      = vehicle.css('h2.listing-row__title')&.text&.squish
      item[:price]      = vehicle.css('span.listing-row__price')&.text&.squish&.delete('^0-9').to_i
      item[:stock_type] = vehicle.css('div.listing-row__stocktype')&.text&.squish
      item[:miles]      = vehicle.css('span.listing-row__mileage')&.text&.squish&.delete('^0-9').to_i
      item[:exterior_color] = vehicle.css('ul.listing-row__meta li')[0]&.text&.squish.gsub('Ext. Color: ', '')
      item[:interior_color] = vehicle.css('ul.listing-row__meta li')[1]&.text&.squish.gsub('Int. Color: ', '')
      item[:transmission] = vehicle.css('ul.listing-row__meta li')[2]&.text&.squish.gsub('Transmission: ', '')
      item[:drivetrain]   = vehicle.css('ul.listing-row__meta li')[3]&.text&.squish.gsub('Drivetrain: ', '')

      Vehicle.where(item).first_or_create
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.paginate(page: params[:page], per_page: 7)

    respond_to do |format|
      format.html
      format.csv { send_data @vehicles.to_csv, filename: "vehicles-#{Date.today}.csv" }
      format.xlsx { response.headers['Content-Disposition'] = "attachment; filename='vehicles.xlsx'" }
      format.pdf do
         render pdf: 'vehicle_list'
      end
    end
  end
  
  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def scrape
    url = 'https://www.cars.com/shopping/sedan/'
    response = VehiclesSpider.process(url)
    if response[:status] == :completed && response[:error].nil?
      flash.now[:notice] = "Successfully scraped url"
    else
      flash.now[:alert] = response[:error]
    end
    rescue StandardError => e
      flash.now[:alert] = "Error: #{e}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_params
      params.require(:vehicle).permit(:title, :stock_type, :exterior_color, :interior_color, :transmission, :drivetrain, :price, :miles)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWebScraper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :stock_type %>
    <%= form.text_field :stock_type %>
  </div>

  <div class="field">
    <%= form.label :exterior_color %>
    <%= form.text_field :exterior_color %>
  </div>

  <div class="field">
    <%= form.label :interior_color %>
    <%= form.text_field :interior_color %>
  </div>

  <div class="field">
    <%= form.label :transmission %>
    <%= form.text_field :transmission %>
  </div>

  <div class="field">
    <%= form.label :drivetrain %>
    <%= form.text_field :drivetrain %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :miles %>
    <%= form.number_field :miles %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<%= button_to 'Scrape', scrape_vehicles_path %>

<h1>Vehicles</h1>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Stock type</th>
      <th>Exterior color</th>
      <th>Interior color</th>
      <th>Transmission</th>
      <th>Drivetrain</th>
      <th>Price</th>
      <th>Miles</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each_with_index do |vehicle, i| %>
      <tr>
        <td><%= i+1 %></td>
        <td><%= vehicle.title %></td>
        <td><%= vehicle.stock_type %></td>
        <td><%= vehicle.exterior_color %></td>
        <td><%= vehicle.interior_color %></td>
        <td><%= vehicle.transmission %></td>
        <td><%= vehicle.drivetrain %></td>
        <td><%= vehicle.price %></td>
        <td><%= vehicle.miles %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class='digg_pagination'>
  <div class='page_info'>
    <%= page_entries_info @vehicles %>
  </div>
  <%= will_paginate @vehicles, :container => false %>
</div>

<div class='text-center'>
  Download file:
  <%= link_to "CSV", vehicles_path(format: "csv") %> |
  <%= link_to "Excel", vehicles_path(format: "xlsx") %> |
  <%= link_to "PDF", vehicles_path(format: "pdf") %>
</div>

app/views/vehicles/index.pdf.erb
<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Stock type</th>
      <th>Exterior color</th>
      <th>Interior color</th>
      <th>Transmission</th>
      <th>Drivetrain</th>
      <th>Price</th>
      <th>Miles</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each_with_index do |vehicle, i| %>
      <tr>
        <td><%= i+1 %></td>
        <td><%= vehicle.title %></td>
        <td><%= vehicle.stock_type %></td>
        <td><%= vehicle.exterior_color %></td>
        <td><%= vehicle.interior_color %></td>
        <td><%= vehicle.transmission %></td>
        <td><%= vehicle.drivetrain %></td>
        <td><%= vehicle.price %></td>
        <td><%= vehicle.miles %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/scrape.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<%= link_to 'Back', root_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @vehicle.title %>
</p>

<p>
  <strong>Stock type:</strong>
  <%= @vehicle.stock_type %>
</p>

<p>
  <strong>Exterior color:</strong>
  <%= @vehicle.exterior_color %>
</p>

<p>
  <strong>Interior color:</strong>
  <%= @vehicle.interior_color %>
</p>

<p>
  <strong>Transmission:</strong>
  <%= @vehicle.transmission %>
</p>

<p>
  <strong>Drivetrain:</strong>
  <%= @vehicle.drivetrain %>
</p>

<p>
  <strong>Price:</strong>
  <%= @vehicle.price %>
</p>

<p>
  <strong>Miles:</strong>
  <%= @vehicle.miles %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>